var gElImgs=[
    '<img onclick="createMeme(this)" id="0" src="img/1.jpg">',
    '<img onclick="createMeme(this)" id="1" src="img/2.jpg">',
    '<img onclick="createMeme(this)" id="2" src="img/3.jpg">',
    '<img onclick="createMeme(this)" id="3" src="img/4.jpg">',
    '<img onclick="createMeme(this)" id="4" src="img/5.jpg">',
    '<img onclick="createMeme(this)" id="5" src="img/6.jpg">',
    '<img onclick="createMeme(this)" id="6" src="img/7.jpg">',
    '<img onclick="createMeme(this)" id="7" src="img/8.jpg">',
    '<img onclick="createMeme(this)" id="8" src="img/9.jpg">',
    '<img onclick="createMeme(this)" id="9" src="img/10.jpg">',
    '<img onclick="createMeme(this)" id="10" src="img/11.jpg">',
    '<img onclick="createMeme(this)" id="11" src="img/12.jpg">',
    '<img onclick="createMeme(this)" id="12" src="img/13.jpg">',
    '<img onclick="createMeme(this)" id="13" src="img/14.jpg">',
    '<img onclick="createMeme(this)" id="14" src="img/15.jpg">',
    '<img onclick="createMeme(this)" id="15" src="img/16.jpg">',
    '<img onclick="createMeme(this)" id="16" src="img/17.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/18.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/19.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/20.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/21.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/22.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/23.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/24.jpg">',
    '<img onclick="createMeme(this)" id="17" src="img/25.jpg">'
];

var gImgs=[
    {id:0,keyWords:['happy','nature']},
    {id:1,keyWords:['mad','politics']},
    {id:2,keyWords:['dogs','cute']},
    {id:3,keyWords:['dogs','babies','cute']},
    {id:4,keyWords:['babies','mad']},
    {id:5,keyWords:['cats']},
    {id:6,keyWords:['funny']},
    {id:7,keyWords:['funny','babies']},
    {id:8,keyWords:['funny']},
    {id:9,keyWords:['mad']},
    {id:10,keyWords:['funny']},
    {id:11,keyWords:['funny']},
    {id:12,keyWords:['funny']},
    {id:13,keyWords:['politics','mad']},
    {id:14,keyWords:['funny','babies','cute']},
    {id:15,keyWords:['funny','dogs']},
    {id:16,keyWords:['politics','funny']},
    {id:17,keyWords:['funny']},
    {id:18,keyWords:['funny']},
    {id:19,keyWords:['funny']},
    {id:20,keyWords:['funny']},
    {id:21,keyWords:['funny']},
    {id:22,keyWords:['funny']},
    {id:23,keyWords:['funny']},
    {id:24,keyWords:['politics']},
    {id:25,keyWords:['funny']},
]
