var gMemes=[
    '<img onclick="createMeme(this)" id="0" src="imgs-square/1.jpg" alt="">',
    '<img onclick="createMeme(this)" id="1" src="imgs-square/2.jpg" alt="">',
    '<img onclick="createMeme(this)" id="2" src="imgs-square/3.jpg" alt="">',
    '<img onclick="createMeme(this)" id="3" src="imgs-square/4.jpg" alt="">',
    '<img onclick="createMeme(this)" id="4" src="imgs-square/5.jpg" alt="">',
    '<img onclick="createMeme(this)" id="5" src="imgs-square/6.jpg" alt="">',
    '<img onclick="createMeme(this)" id="6" src="imgs-square/7.jpg" alt="">',
    '<img onclick="createMeme(this)" id="7" src="imgs-square/8.jpg" alt="">',
    '<img onclick="createMeme(this)" id="8" src="imgs-square/9.jpg" alt="">',
    '<img onclick="createMeme(this)" id="9" src="imgs-square/10.jpg" alt="">',
    '<img onclick="createMeme(this)" id="10" src="imgs-square/11.jpg" alt="">',
    '<img onclick="createMeme(this)" id="11" src="imgs-square/12.jpg" alt="">',
    '<img onclick="createMeme(this)" id="12" src="imgs-square/13.jpg" alt="">',
    '<img onclick="createMeme(this)" id="13" src="imgs-square/14.jpg" alt="">',
    '<img onclick="createMeme(this)" id="14" src="imgs-square/15.jpg" alt="">',
    '<img onclick="createMeme(this)" id="15" src="imgs-square/16.jpg" alt="">',
    '<img onclick="createMeme(this)" id="16" src="imgs-square/17.jpg" alt="">',
    '<img onclick="createMeme(this)" id="17" src="imgs-square/18.jpg" alt="">'
];